### ISSUE TITLE
HTTP401について

### ISSUE THREAD

**Issue by mizushima1226** [kamiyakoh/any-memos-app#2]
この処理ってどんな想定でしたでしょうか？
（どのようなユーザーの操作を想定しているか？）
https://github.com/kamiyakoh/any-memos-app/blob/ddce7cd6bce2fdabe33129b7bf4fe4c5e3eb3ea5/src/hooks/useMemos.ts#L228-L230

認証エラーを意味するステータスコードに対して、処理の内容が、
権限がないので、再ログインをさせているところに違和感ありました！

**Comment by kamiyakoh** [comment]
トークン期限内にアプリを開いて、開いたまま時間が経過し、
トークン期限切れの状態でメモの作成・編集更新・削除を行うと、
apiがデータの変更を拒否します。

なので、ユーザーはリロードした後、再ログインしてトークンを更新しない限り、
メモの作成・編集更新・削除を正常に行えません。

handle401は上記の状態での正常にメモの操作が行えない事の表示と
ユーザーが手動でリロードするのを省く目的のものです。

**Comment by mizushima1226** [comment]
解説ありがとうございます！
でしたら権限がない、というより、シンプルに再ログインして欲しいって感じですね！
かなり細かいところなので認識だけ持っていただければokと思いました！
